### ISSUE TITLE
Can I change the RGB pin?

### ISSUE THREAD

**Issue by qlalfdu** [2dom/PxMatrix#275]
I use ESP32 WROOM32
I want to change the RGB pins, is it possible?
Thank you.

**Comment by lg007** [comment]
Hello,

What do you mean by 

> I want to change the RGB pins, is it possible?

The following snippet:

```
// Pins for LED MATRIX
#ifdef ESP32

#define P_LAT 22
#define P_A 19
#define P_B 23
#define P_C 18
#define P_D 5
#define P_E 15
#define P_OE 16
...
...

#endif
```

is where you define which ESP32 pins are used for the communication between the ESP32 and the RGB matrix. You can use any pin as long as it is an output pin on the ESP32 and it is not used by anything else. Eg. I am using pin 26 of the ESP32 for latching, therefore in my code you could see:

`#define P_LAT 26 `

There is also another pin which is used but not defined here: pin 13, which is the output of the SPI register. I don't know if this can be changed or not, they say that on the ESP32 you can almost change any pin, but I would leave that this way (it is defined in the library itself - in the PxMatrix.h file).

**Comment by qlalfdu** [comment]
![PN20-1552](https://user-images.githubusercontent.com/24924909/121804324-c4871780-cc80-11eb-8a84-e9c79f751d4f.png)
I want to change the RGB pins in the red square, but there is no content in the sketch.
Is there any way?

**Comment by lg007** [comment]
The whole library is based on the chaining of the red, green and blue channels of the RGB display. The output of the SPI register of the ESP 32 is connected to the R1 input of the RGB display. Therefore you "feed" the display on the R1 (red 1) input channel. The output of the R1 channel is connected to the input of the R2 channel. The output of the R2 channel is connected to the input of the G1 (green 1) channel, and so on... So you will have a long shift register where channels R1, R2, G1, G2, B1 and B2 are chained together. 

The library allows you to change this order programatically with the following instruction:
`display.setColorOrder({{colororder}});`
where 
`{{colororder}} `
can be the following:
`RRGGBB, RRBBGG, GGRRBB, GGBBRR, BBRRGG, BBGGRR`

This function is needed because the quality assurance in the manufacturing of these displays is sometimes "missing"

I hope I answered your question.

**Comment by qlalfdu** [comment]
I understand.
Thank you kindly explain.
Thank you lg007.
