### ISSUE TITLE
Seems doesn't work

### ISSUE THREAD

**Issue by federicoprimomo** [2dom/PxMatrix#83]
Hi, pattern test does not look good, any ideas?
![WhatsAppVideo20190408at15](https://user-images.githubusercontent.com/6616280/55748764-dcfea600-5a15-11e9-89a6-9c11db7c96e5.gif)

**Comment by 2dom** [comment]
Looks perfekt to me ... 1/4 scan with scan pattern ZIGZAG

**Comment by federicoprimomo** [comment]
Ok, I set scan pattert to zigzag, but, see this image. It's supposed to display "HOLA"
Thanks.
  display.setTextColor(myCYAN);
  display.setCursor(2,0);
  display.print("HOLA");
![WhatsApp Image 2019-04-09 at 08 56 03](https://user-images.githubusercontent.com/6616280/55798515-8476e980-5aa5-11e9-84f7-12866d19867b.jpeg)

**Comment by federicoprimomo** [comment]
Another example, this image should display a "O"

![WhatsApp Image 2019-04-09 at 08 59 54](https://user-images.githubusercontent.com/6616280/55798686-f5b69c80-5aa5-11e9-8b99-c7a95a72e56e.jpeg)

**Comment by GeorgeFlorian** [comment]
From your pictures it seems that the LED Display is a P10 32x16. That kind of display can have the following Scan Pattern: 1/2, 1/4 or 1/8.
That means 3 different options: `display.begin(2)` , `display.begin(4)` and finally `display.begin(8)`.
Ok ?

So try using `display.begin(2)` first and see what happens. Then try `display.begin(4)`. And then `display.begin(8)`.

If none is working properly try adding `display.setScanPattern(LINE);` and `display.setMuxPattern(BINARY)` to the mix.

Like so: 

```
display.begin(2); // or you can use display.begin(4); or display.begin(8);
display.setScanPattern(LINE); // or try ZIGZAG, ZAGGIZ, WZAGZIG, VZAG
display.setMuxPattern(BINARY); // or you can use display.setMuxPattern(STRAIGHT);
```

Not all displays need `display.setScanPattern();` and `display.setMuxPattern()`. You need to experiment and see what works for you.

Read the documentation and try to understand it, because it's all in there on how to set it up.
